---
title: "Quantitative Forschung"
output: html_notebook
---

#1. Install Package
```{r}
install.packages("devtools")
library("devtools")
devtools::install_github("GPclips/qF")
```

#2. Load Package
```{r}
library("qF")
```

#3. Load Resources
```{r}
init_projekt()
```

#4. Hypothese 1
```{r}
#Prepare Data
dataH1 <- prepareDataH1()

#Graphical Printout
bargraph(~toJapan | gender, success = "Yes", data = dataH1, type = "percent", main = "Percent Male and Female applying for Japan", xlab = "Applying for Japan", ylab = "Percentage")
cat("------------------------ Absolute: students going to Japan (by gender)", fill=TRUE)
prop(toJapan~gender, success = "Yes", data = dataH1, format = "count")
cat("------------------------ Percent: students going to Japan (by gender)", fill=TRUE)
prop(toJapan~gender, success = "Yes", data = dataH1)

cat("------------------------ Percent: students going to Japan (by gender of all data)", fill=TRUE)
toJapan <- dataH1 %>% filter(requestedCountry == "Japan")

cat("Percent: female going to Japan (by gender of all data)", fill=TRUE)
femaleToJapan <- toJapan %>% filter(gender == "Female")
nrow(femaleToJapan)/nrow(dataH1)
cat("Percent: male going to Japan (by gender of all data)", fill=TRUE)
maleToJapan <- toJapan %>% filter(gender == "Male")
propMaleToJapan <- nrow(maleToJapan)/nrow(dataH1)
propMaleToJapan

#Analyze Data
cat("------------------------ Bootstrap: Female going to Japan", fill=TRUE)
cnt <- 10000
cat(cnt, fill=TRUE, labels = "Using n Iterations: ")
cat("Bootstrap: Percent Female going to Japan", fill=TRUE)
bootPercentFemaleOfDataH1 <- analyzePercentJapan(dataH1, cnt)
histogram(~ bootPercentFemaleOfDataH1$t, xlab = "Percent Female", ylab = "Density", main="Percent Female going to Japan")
cat("Bootstrap: Abs Female going to Japan", fill=TRUE)
bootAbsFemaleOfDataH1 <- analyzeAbsJapan(dataH1, cnt)
histogram(~ bootAbsFemaleOfDataH1$t, xlab = "Abs Female", ylab = "Density", main="Abs Female going to Japan")

cat("------------------------ Calculate pValue of percent calculation", fill=TRUE)
bwplot(bootPercentFemaleOfDataH1$t, xlab ="Bootstrap: percent female", main="Percent Female going to Japan")
favstats(bootPercentFemaleOfDataH1$t)
pValueH1percentCalc <- prop(~ t <= propMaleToJapan, data = bootPercentFemaleOfDataH1)
cat(pValueH1percentCalc, fill=TRUE, labels = "pValue (percent): ")

cat("------------------------ Calculate pValue of abs calculation", fill=TRUE)
bwplot(bootAbsFemaleOfDataH1$t, xlab ="Bootstrap: abs female", main="Abs Female going to Japan")
favstats(bootAbsFemaleOfDataH1$t)
pValueH1AbsCalc <- prop(~ t <= nrow(maleToJapan), data = bootAbsFemaleOfDataH1)
cat(pValueH1AbsCalc, fill=TRUE, labels = "pValue (abs): ")
```

#5. Hypothese 2
```{r}
#Prepare Data
dataH2 <- prepareDataH2()

#Graphical printout
xyplot(timeSpanOpportunityToDeal ~ ageInYears, data=dataH2, xlab="Customers' Age [Years]", ylab="Time span from oportunity to deal [Day(s)]", main="Time span from oportunity to deal [Day(s)] ~ Customers' Age [Years]")

#Remove Outliers
dataH2 <- dataH2 %>% filter(ageInYears <= 25) %>% filter(timeSpanOpportunityToDeal <= 600)
cat(nrow(dataH2), fill = TRUE, labels = "Using n after removing outliers: ")

xyplot(timeSpanOpportunityToDeal ~ ageInYears, data=dataH2, xlab="Customers' Age [Years]", ylab="Time span from oportunity to deal [Day(s)]", main="Time span from oportunity to deal [Day(s)] ~ Customers' Age [Years]")

#Analyze data
cat("------------------------ Bootstrap: Covariance and Correlation Coefficient", fill=TRUE)
cnt <- 10000
cat(cnt, fill=TRUE, labels = "Using n Iterations: ")
c <- analyzeCovariance(dataH2, cnt)
histogram(~ c$t, xlab = "Covariance", ylab = "Density", main="COV(Customers' Age [Years], Time span from oportunity to deal [Day(s)])")

cc <- analyseCorrelationCoefficient(dataH2, cnt)
histogram(~ cc$t, xlab = "Correlation Coefficient", ylab = "Density", main="COR(Customers' Age [Years], Time span from oportunity to deal [Day(s)])")

cat("------------------------ LM: timeSpanOpportunityToDeal ~ ageInYears", fill=TRUE)
lmH2 <- lm(y ~ x, data=dataH2)
cat("------ Summary ------", fill=TRUE)
summary(lmH2)

cat("------ Anova ------", fill=TRUE)
anova(lmH2)
plotLm(dataH2, "Customers' Age [Years]", "Time span from oportunity to deal [Day(s)]", "Time span from oportunity to deal [Day(s)] ~ Customers' Age [Years]")

```

#6. Hypothese 3
```{r}
#Prepare Data
dataH3 <- prepareDataH3()

#Graphical printout
xyplot(amountStudents ~ billion_eur, data=dataH3, xlab="BIP/Year [Billion Euros]", ylab="Amount Students/Year", main="Amount Students/Year ~ BIP/Year [Billion Euros]")

#Analyze data
cat("------------------------ Bootstrap: Covariance and Correlation Coefficient", fill=TRUE)
cnt <- 10000
cat(cnt, fill=TRUE, labels = "Using n Itterations: ")
c <- analyzeCovariance(dataH3, cnt)
histogram(~ c$t, xlab = "Covariance", ylab = "Density", main="COV(Amount Students/Year, BIP/Year [Billion Euros])")

cc <- analyseCorrelationCoefficient(dataH3, cnt)
histogram(~ cc$t, xlab = "Correlation Coefficient", ylab = "Density", main="COR(Amount Students/Year, BIP/Year [Billion Euros])")

cat("------------------------ LM: amountStudents ~ billion_eur", fill=TRUE)
lmH3 <- lm(amountStudents ~ billion_eur, data=dataH3)
plotLm(dataH3, "BIP (Billion Euros)", "Amount Students/Year", "Amount Students/Year ~ BIP [Billion Euros]")

cat("------ Summary ------", fill=TRUE)
summary(lmH3)

cat("------ Anova ------", fill=TRUE)
anova(lmH3)
```
